apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-volume
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/mysql"
    type: DirectoryOrCreate
  claimRef:
    name: mysql-volum-claim
    namespace: default

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-volume-claim
spec:
  # storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi

# ---

# apiVersion: v1
# kind: PersistentVolume
# metadata:
#   name: influxdb-data
#   labels:
#     type: local
# spec:
#   storageClassName: manual
#   accessModes:
#     - ReadWriteOnce
#   capacity:
#     storage: 1Gi
#   hostPath:
#     path: "/mnt/influx"
#     type: DirectoryOrCreate
#   claimRef:
#     name: influxdb-data-disk
#     namespace: default

# ---

# apiVersion: v1
# kind: PersistentVolumeClaim
# metadata:
#   name: influxdb-data-disk
# spec:
#   accessModes:
#     - ReadWriteOnce
#   resources:
#     requests:
#       storage: 1Gi