apiVersion: v1
kind: Service
metadata:
  name: nginx-svc
spec:
  selector:
    app: nginx        #привязываем сервис к нашему контейнеру
  type: LoadBalancer  #указываем тип
  ports:
    - protocol: TCP
      name: ssh
      port: 22
      targetPort: 22
    - protocol: TCP
      name: http
      port: 80        #какой порт хотим открыть
      targetPort: 80  #к какому порту хотим присоединиться
    - protocol: TCP
      name: https
      port: 443        #какой порт хотим открыть
      targetPort: 443
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx_image
        imagePullPolicy: Never
        ports:
        - containerPort: 22
        - containerPort: 80
        - containerPort: 443